import {afterEach, expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen} from '@testing-library/react';
import PDFImport from './pdf-import';
const mock=vi.hoisted(()=>vi.fn());
vi.mock('./financial-pdf',()=>({financialPDF:mock}));
afterEach(()=>{cleanup();vi.resetAllMocks();});
it('requires reconciliation and confirmation, and invalidates output on layout changes',async()=>{
 mock.mockResolvedValue({csv:'Paid\r\n10.00',rows:1,records:[{amount:'10.00'}]});
 const onPrepared=vi.fn();
 render(<PDFImport file={new File(['test'],'statement.pdf')} profile={{columns:{amount:'Paid'},delimiter:',',date_format:'%Y-%m-%d',allowed_values:{}}} onPrepared={onPrepared} />);
 fireEvent.click(screen.getByRole('button',{name:'Extract financial rows locally'}));
 const confirm=await screen.findByRole('button',{name:'Confirm extracted rows for import'});
 expect((confirm as HTMLButtonElement).disabled).toBe(true);
 fireEvent.change(screen.getByLabelText('Expected paid total for selected rows'),{target:{value:'11.00'}});
 expect((confirm as HTMLButtonElement).disabled).toBe(true);
 fireEvent.change(screen.getByLabelText('Expected paid total for selected rows'),{target:{value:'10.00'}});
 fireEvent.click(confirm);expect(onPrepared).toHaveBeenLastCalledWith(expect.any(Blob));
 fireEvent.change(screen.getByLabelText('Table top (%)'),{target:{value:'25'}});
 expect(onPrepared).toHaveBeenLastCalledWith(null);
 expect(screen.queryByRole('button',{name:'Confirm extracted rows for import'})).toBeNull();
});
